import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./auth/_components/Navbar";
import Footer from "./auth/_components/Footer";
import NextAuthProvider from "@/providers/components/nextauth.providers";
import Providers from "@/providers/components/ReactQueryPrvider.provider";
import { ToastContainer, toast } from 'react-toastify';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <ToastContainer />
        <div className="flex flex-col justify-between min-h-screen ">
          <NextAuthProvider>
          <Navbar/>
       <div className="container">
          {children}
        </div>
        <Footer/>
        </NextAuthProvider>
        </div>
     
        </Providers>
      </body>
    </html>
  );
}
